trigger:
  branches:
    include:
      - main
      - stable
      - gh-readonly-queue/main/*

pr:
  branches:
    include:
      - '*'

pool:
  name: agent-pool-onprem-ubuntu
  # demands: Agent.CPU -equals 8

schedules:
  - cron: "0 0 1 * *"
    displayName: Monthly scheduled build
    branches:
      include:
        - main
    always: true
  - cron: "0 0 * * *"
    displayName: Daily scheduled build
    branches:
      include:
        - stable
    always: true

variables:
  ociServiceConnection: oci-service-connection-jbpf
  acr: jbpfpipeline
  baseImageMajor: 1
  baseImageMinor: $[counter(format('{0}.base',variables['baseImageMajor']),0)]
  containerRegistry: $[format('{0}.azurecr.io',variables['acr'])]
  DOCKER_BUILDKIT: 1
  imageTag: "$[format('pipeline-{0}-{1}', replace(variables['build.buildnumber'], '.', '-'), variables['build.sourceversion'])]"

resources:
  repositories:
    - repository: templates
      type: git
      name: 5GRack/PipelineTemplates
      ref: refs/heads/main

stages:
  - stage: CheckVars
    displayName: Environment
    jobs:
      - job: CheckVars
        displayName: Environment
        steps:
          - template: environment/print.yaml@templates
            parameters:
              rootParameters: ${{ parameters }}

  - stage: Guardian
    jobs:
      - job: guardian
        pool:
          vmImage: windows-latest
        displayName: Guardian
        steps:
          # Don't checkout submodules, because we don't want to run the guardian checks on 3P code.
          - checkout: self
            submodules: false
          - template: agentpool/guardian-checks.yaml@templates

  - stage: ComponentsGoverance
    dependsOn: []
    jobs:
      - job: componentsgovernance
        displayName: Components Governance
        steps:
          - template: agentpool/component-governance.yaml@templates
            parameters:
              outputformat: 'text'
              outputfile: '$(System.DefaultWorkingDirectory)/NOTICE'

  - stage: HouseKeeping
    dependsOn: []
    jobs:
      - job: housekeeping
        displayName: House Keeping
        workspace:
          clean: all
        steps:
          - template: agentpool/cleanup.yaml@templates

          - template: pipeline/print-debug-info.yaml

          - template: pipeline/house-keeping.yaml

          - template: agentpool/cleanup.yaml@templates

  - template: pipeline/build-for-os.yaml

  - stage: Doxygen
    dependsOn: []
    displayName: Doxygen
    jobs:
      - job: doxygen
        displayName: Doxygen
        steps:
          - template: pipeline/doxygen.yaml
