parameters:
  - name: dockerTypes
    displayName: "Configuration Types"
    type: object
    default:
      - value: "mariner"
        displayName: "CBL-Mariner"
        id: "mariner"
      - value: "ubuntu22.04"
        displayName: "Ubuntu 22.04"
        id: "ubuntu22_04"
      - value: "ubuntu20.04"
        displayName: "Ubuntu 20.04"
        id: "ubuntu20_04"

  - name: testCases
    displayName: Test Cases
    type: object
    default:
      - description: "Dynamic"
        id: test0
        staticBuildParam: ""
        sanitizerBuildParam: ""

      - description: "Static"
        id: test1
        staticBuildParam: "-e JBPF_STATIC=1"
        sanitizerBuildParam: ""

      - description: "Dynamic with ASAN"
        id: test2
        staticBuildParam: ""
        sanitizerBuildParam: "-e SANITIZER=1"

      - description: "Static with ASAN"
        id: test3
        staticBuildParam: "-e JBPF_STATIC=1"
        sanitizerBuildParam: "-e SANITIZER=1"

      - description: "Experimental Features, Dynamic with ASAN"
        id: test4
        staticBuildParam: ""
        sanitizerBuildParam: "-e SANITIZER=1 -e JBPF_EXPERIMENTAL_FEATURES=1"

      - description: "Experimental Features, Static with ASAN"
        id: test5
        staticBuildParam: "-e JBPF_STATIC=1 -e JBPF_EXPERIMENTAL_FEATURES=1"
        sanitizerBuildParam: "-e SANITIZER=1"

      - description: "Experimental Features, Dynamic"
        id: test6
        staticBuildParam: ""
        sanitizerBuildParam: "-e JBPF_EXPERIMENTAL_FEATURES=1"

      - description: "Experimental Features, Static"
        id: test7
        staticBuildParam: "-e JBPF_STATIC=1 -e JBPF_EXPERIMENTAL_FEATURES=1"
        sanitizerBuildParam: ""

stages:
  - stage: CoverageTests
    displayName: CoverageTests
    dependsOn: []
    jobs:
      - job: Cleanup
        displayName: Cleanup
        condition: always()
        steps:
          - template: agentpool/cleanup.yaml@templates
      - job: BuildAndRunCoverageTests
        dependsOn: Cleanup
        displayName: BuildAndRunCoverageTests
        steps:
          - template: agentpool/cleanup.yaml@templates
          - template: print-debug-info.yaml
          - template: build-lib.yaml
            parameters:
              dockerType: ubuntu22.04
          - bash: |
              set -x
              if ! docker run --init --privileged --network host --cap-add=SYS_ADMIN --shm-size=1g --mount type=tmpfs,destination=/dev/shm -v `pwd`:/jbpf_out_lib -v `pwd`/build:/jbpf/build -e JBPF_PATH=/jbpf -e CLANG_FORMAT_CHECK=1 -e JBPF_COVERAGE=1 -e JBPF_DEBUG=1 $(containerRegistry)/jbpf-lib-ubuntu22.04:$(imageTag); then
                  echo ERROR Running Coverage Tests
                  exit 1
              fi
              cat build/Testing/Temporary/LastTest.log
              cp build/Testing/Temporary/LastTest.log $(Build.ArtifactStagingDirectory)
              cp -R `pwd`/out/jbpf_coverage.xml $(Build.ArtifactStagingDirectory)
            displayName: Run Coverage Tests
            continueOnError: false
          - task: PublishBuildArtifacts@1
            condition: always()
            inputs:
              ArtifactName: artifacts
          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk'
            inputs:
              packageType: sdk
              version: 6.0.x
              installationPath: $(Agent.ToolsDirectory)/dotnet
          # Publish code coverage results v1
          # Publish Cobertura or JaCoCo code coverage results from a build.
          - task: PublishCodeCoverageResults@2
            inputs:
              codeCoverageTool: 'Cobertura' # 'Cobertura' | 'JaCoCo'. Required. Code coverage tool. Default: JaCoCo.
              summaryFileLocation: 'out/jbpf_coverage.xml'
              #pathToSources: # string. Path to Source files.
              #reportDirectory: # string. Report directory.
              #additionalCodeCoverageFiles: # string. Additional files.
              #failIfCoverageEmpty: false # boolean. Fail when code coverage results are missing. Default: false.

          - template: agentpool/cleanup.yaml@templates

  - ${{ each dockerType in parameters.dockerTypes }}:
      - stage: ${{ dockerType.id }}
        displayName: ${{ dockerType.displayName }}
        dependsOn: []
        jobs:
          - ${{ each testCase in parameters.testCases }}:
              - job: ${{ testCase.id }}_${{ dockerType.id }}
                dependsOn: []
                displayName: Test - ${{ testCase.description }}
                workspace:
                  clean: all
                steps:
                  - template: agentpool/cleanup.yaml@templates
                  - template: setup-on-vm.yaml
                  - template: print-debug-info.yaml
                  - template: build-lib.yaml
                    parameters:
                      dockerType: ${{ dockerType.value }}
                  - template: standard-tests.yaml
                    parameters:
                      dockerType: ${{ dockerType.value }}
                      testCase: ${{ testCase }}
                  - template: agentpool/cleanup.yaml@templates

                  - template: agentpool/cleanup.yaml@templates

